import { Board, User } from "@prisma/client";
import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import BoardsList from "../components/BoardsList";
import CreateBoard from "../components/CreateBoard";
import { createBoard } from "../handlers/boards";

import prisma from "../lib/prisma";

import styles from "../styles/Home.module.css";
import { FormattedBoard, FormattedUser } from "../types";

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  user,
  boards,
}) => {
  console.log(user, boards);

  const handleSubmit = async (name: string) => {
    try {
      await createBoard({ name, userId: user?.id || "" });
    } catch (error) {
      console.log(error);
    }
  };

  if (!user) {
    return (
      <div>
        <p>Loading</p>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Track Your Job Applications</h1>
        <p>
          Hey {user.firstName} {user.lastName}
        </p>
        <CreateBoard onSubmit={handleSubmit} />
        {!!boards.length && <BoardsList boards={boards} />}
      </main>

      <footer className={styles.footer}>yo</footer>
    </div>
  );
};

type IndexProps = {
  user: FormattedUser | null;
  boards: FormattedBoard[];
};

export const getStaticProps: GetStaticProps<IndexProps> = async () => {
  const data = await prisma.user.findFirst({
    where: { id: "888ab0a8-b32c-47e1-9882-7a4136d1d1f2" },
  });

  const boardsData = await prisma.board.findMany();

  if (!data) {
    return { props: { user: null, boards: [] } };
  }

  const user: FormattedUser = {
    ...data,
    createdAt: data.createdAt.toISOString(),
  };

  const boards = boardsData.map((board) => ({
    ...board,
    createdAt: board.createdAt.toISOString(),
  }));

  return { props: { user, boards } };
};

export default Home;
